environment:
  NugetApiKey:
    secure: pUOD7LFENqKpwiR0xr3tRDyHz0p4EQE+7ClpmtuZCFSJUOd7hHuDie8+a0Bvqvab


# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

build: false

#Kick off the CI/CD pipeline
test_script:
- ps: . .\build.ps1